# Google App Engine deployment configuration
runtime: python311

# Environment variables
env_variables:
  PORT: 8080
  PYTHONUNBUFFERED: 1

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Resource requirements
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Network settings
network:
  forwarded_ports:
    - 8080

# Health check
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2