agents:
  market:
    commission_rate: 0.03
    crops:
      corn:
        base_price: 0.85
        seasonality: 0.2
        volatility: 0.1
      tomatoes:
        base_price: 3.5
        seasonality: 0.3
        volatility: 0.15
      wheat:
        base_price: 0.65
        seasonality: 0.15
        volatility: 0.08
    enabled: true
    initial_balance: 2000.0
    quality_multipliers:
      A: 1.2
      B: 1.0
      C: 0.8
    update_interval: 300
  prediction:
    enabled: true
    initial_balance: 1500.0
    models:
      harvest_timing:
        crop_cycle_days: 90
        enabled: true
      irrigation_need:
        confidence_threshold: 0.6
        data_sources:
        - soil_moisture
        - temperature
        - humidity
        enabled: true
      pest_risk:
        confidence_threshold: 0.7
        enabled: true
      weather_forecast:
        confidence_threshold: 0.5
        enabled: true
        forecast_hours: 24
    pricing:
      harvest_timing: 5.0
      irrigation_need: 2.0
      pest_risk: 3.0
      weather_forecast: 1.5
    update_interval: 1800
  resource:
    enabled: true
    initial_balance: 5000.0
    pricing:
      equipment: 15.0
      fertilizer: 2.5
      labor: 12.0
      water: 0.05
    resources:
      equipment:
        harvesters: 1
        irrigation_pumps: 4
        sprayers: 3
        tractors: 2
      fertilizer:
        application_rate: 25
        inventory:
          nitrogen: 500
          phosphorus: 300
          potassium: 400
      labor:
        available_workers: 8
        hourly_rates:
          basic: 10
          expert: 15
          intermediate: 12
      water:
        efficiency_bonus: 0.15
        peak_hours:
        - 6
        - 18
        total_capacity: 10000
    update_interval: 3600
  sensor:
    enabled: true
    initial_balance: 1000.0
    pricing:
      humidity: 0.3
      pest_detection: 1.0
      soil_moisture: 0.5
      temperature: 0.3
    sensors:
      humidity:
        enabled: true
        optimal:
        - 40
        - 70
        range:
        - 30
        - 95
      pest_detection:
        confidence_threshold: 0.7
        enabled: true
      soil_moisture:
        enabled: true
        optimal:
        - 0.3
        - 0.6
        range:
        - 0.1
        - 0.8
      temperature:
        enabled: true
        optimal:
        - 18
        - 28
        range:
        - 5
        - 45
    update_interval: 300
degraded_mode:
  cache_expiry_hours: 6
  enabled: true
  fallback_data_age_limit_hours: 24
  offline_detection_timeout: 30
  rule_based_confidence: 0.4
farms:
  farm_1:
    coordinates:
    - 36.7378
    - -119.7871
    crop_type: tomatoes
    farm_size_acres: 50
    location: fresno_ca
  farm_2:
    coordinates:
    - 37.6391
    - -120.9969
    crop_type: corn
    farm_size_acres: 120
    location: modesto_ca
  farm_3:
    coordinates:
    - 36.6777
    - -121.6555
    crop_type: lettuce
    farm_size_acres: 80
    location: salinas_ca
logging:
  backup_count: 5
  file_logging: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_directory: logs
  max_log_size_mb: 100
  transaction_logging: true
simulation:
  accelerated_time: false
  api_failure_chance: 0.1
  demo_duration_minutes: 10
  demo_mode: true
  network_failure_chance: 0.05
  time_multiplier: 1.0
system:
  environment: development
  log_level: INFO
  max_agents: 20
  message_ttl_hours: 24
  offline_mode: false
  region: california_central_valley
  simulation_speed: 1.0
